export enum ActionTypes {
  ADD_TRANSACTION_REQUEST = "ADD_TRANSACTION_REQUEST",
  ADD_TRANSACTION_RESULT = "ADD_TRANSACTION_RESULT",
  ADD_TRANSACTION_ERROR = "ADD_TRANSACTION_ERROR",
  DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST",
  DELETE_TRANSACTION_RESULT = "DELETE_TRANSACTION_RESULT",
  DELETE_TRANSACTION_ERROR = "DELETE_TRANSACTION_ERROR",
  GET_ALL_TRANSACTIONS_REQUEST = "GET_ALL_TRANSACTIONS_REQUEST",
  GET_ALL_TRANSACTIONS_RESULT = "GET_ALL_TRANSACTIONS_RESULT",
  GET_ALL_TRANSACTIONS_ERROR = "GET_ALL_TRANSACTIONS_ERROR",
}
