name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "Welcome to First Github Actions jobs"

      - name: List files
        run: ls

      - name: Read file
        run: cat FinanceTracking-UI/README.md
