name: Generate ASCII Workflow

on: push

jobs:
  generate-ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Cgheckout Repository
        uses: actions/checkout@v4

      - name: List Repo files
        run: ls -ltra

      - name: Executing Shell Script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh

    #   - name: Install Cowsay Program
    #     run: sudo apt-get install cowsay -y

    #   - name: Execture Cowsay CMD
    #     run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt

    #   - name: Test file existance
    #     run: grep -i "dragon" dragon.txt

    #   - name: Read File
    #     run: cat dragon.txt
