name: Generate ASCII Workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execture Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt

      - name: Upload a Dragon Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dragon-artifact
          path: dragon.txt

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Download a Dragon Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: dragon-artifact

      - name: Test file existance
        run: grep -i "dragon" dragon.txt

  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Download a Dragon Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: dragon-artifact

      - name: Read file
        run: cat dragon.txt

      - name: Deploy to Production
        run: echo "Deploying to Production"
