name: Generate ASCII Workflow

on: push

jobs:
  generate-ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Cgheckout Repository
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execture Cowsay CMD
        run: |
          echo "Generating ASCII art..."
          cowsay -f dragon "Welcome to Finance Tracking UI" >> dragon.txt

      - name: Test file existance
        run: grep -i "dragon" dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: List Repo files
        run: ls -ltra
