name: Generate ASCII Workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execture Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt

      - name: Sleeps for 30 seconds
        run: sleep 30

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Sleeps for 10 seconds
        run: sleep 10

      - name: Test file existance
        run: grep -i "dragon" dragon.txt

  deploy_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Read file
        run: cat dragon.txt

      - name: Deploy to Production
        run: echo "Deploying to Production"
